name: CI - Anomaly Detection Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cml

      - name: Exécution du script d'anomalie
        run: |
          
          python train.py

      - name: Upload des artefacts générés
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifacts
          path: |
            artifacts/
            figures/
            models/
            *.py

      - name: Publication des résultats avec CML
        run: |
          # Publication du contenu des dossiers via CML
          cml-publish artifacts/ --md "### Dossier Artifacts"
          cml-publish figures/ --md "### Dossier Figures"
          cml-publish models/ --md "### Dossier Models"
