name: CI - Anomaly Detection Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc dvc[gs]

      - name: Exécution du script d'anomalie
        run: |
          python train.py

      - name: Upload des artefacts générés
        uses: actions/upload-artifact@v4
        with:
          name: repo-artifacts
          path: |
            artifacts/
            figures/
            models/
            *.py

      - name: Publication des résultats
        run: |
          # Create a markdown report
          echo "## Pipeline Results" > report.md
          echo "### Generated Artifacts" >> report.md
          ls -R artifacts/ >> report.md
          echo "### Generated Figures" >> report.md
          ls -R figures/ >> report.md
          echo "### Generated Models" >> report.md
          ls -R models/ >> report.md
